project:
  type: website
  output-dir: docs

# Meta
description-meta: "Course on Methodology of Economic Research"
author-meta: "Lauren Chenarides"

website:
  title: "AREC/ECON 570 Methodology of Economic Research"
  description: "Course on Methodology of Economic Research"
  navbar:
    background: light
    left:
      - text: Syllabus
        href: 2026/syllabus.qmd
      - text: "Fall 2026"
        menu:
          - text: Schedule
            href: 2026/schedule.qmd
          - text: Readings
            href: 2026/readings.qmd
          - text: Lectures
            href: lectures/lectures.qmd

    right: 
      - icon: github
        href: https://github.com/laurenchenarides/csu-arec-570
  page-navigation: true
  page-footer: 
    left: "[Lauren Chenarides](https://github.com/laurenchenarides/csu-arec-570) &copy; <script>document.write(new Date().getFullYear())</script>" 
    right: 
      - icon: github
        href: https://github.com/laurenchenarides/csu-arec-570
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/laurenchenarides/csu-arec-570
  repo-actions: [edit, issue, source]
  open-graph: true
  site-url: "https://laurenchenarides.github.io/csu-arec-570"
  # google-analytics:
  #   tracking-id: "G-GG4GM3TPXK"
  #   anonymize-ip: false

bibliography: readings.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    citations-hover: true
    footnotes-hover: true
    link-external-icon: false
    link-external-newwindow: true

execute: 
  freeze: auto

comments:
  hypothesis: false
  

