<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lauren Chenarides">
<meta name="description" content="Course on Methodology of Economic Research">

<title>Syllabus – AREC/ECON 570 Methodology of Economic Research</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c7ab57aa33037bad7520c6cb9ec7d6ec.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Syllabus – AREC/ECON 570 Methodology of Economic Research">
<meta property="og:description" content="AREC 310 (Fall 2025)">
<meta property="og:site_name" content="AREC/ECON 570 Methodology of Economic Research">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">AREC/ECON 570 Methodology of Economic Research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../2026/syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-fall-2026" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Fall 2026</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-fall-2026">    
        <li>
    <a class="dropdown-item" href="../2026/schedule.html">
 <span class="dropdown-text">Schedule</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2026/readings.html">
 <span class="dropdown-text">Readings</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../lectures/lectures.html">
 <span class="dropdown-text">Lectures</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/laurenchenarides/csu-arec-570"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#course-information" id="toc-course-information" class="nav-link active" data-scroll-target="#course-information">Course Information</a></li>
  <li><a href="#course-links" id="toc-course-links" class="nav-link" data-scroll-target="#course-links">Course Links</a></li>
  <li><a href="#course-description" id="toc-course-description" class="nav-link" data-scroll-target="#course-description">Course Description</a></li>
  <li><a href="#prerequisite-arececon-202-principles-of-microeconomics" id="toc-prerequisite-arececon-202-principles-of-microeconomics" class="nav-link" data-scroll-target="#prerequisite-arececon-202-principles-of-microeconomics">Prerequisite: AREC/ECON 202 (Principles of Microeconomics)</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#course-material" id="toc-course-material" class="nav-link" data-scroll-target="#course-material">Course Material</a>
  <ul class="collapse">
  <li><a href="#required" id="toc-required" class="nav-link" data-scroll-target="#required">Required</a></li>
  <li><a href="#optional-resource" id="toc-optional-resource" class="nav-link" data-scroll-target="#optional-resource">Optional Resource</a></li>
  </ul></li>
  <li><a href="#assignments-grading" id="toc-assignments-grading" class="nav-link" data-scroll-target="#assignments-grading">Assignments &amp; Grading</a>
  <ul class="collapse">
  <li><a href="#grading-policies" id="toc-grading-policies" class="nav-link" data-scroll-target="#grading-policies">Grading Policies</a></li>
  <li><a href="#attendance-policy" id="toc-attendance-policy" class="nav-link" data-scroll-target="#attendance-policy">Attendance Policy</a></li>
  <li><a href="#make-up-policy" id="toc-make-up-policy" class="nav-link" data-scroll-target="#make-up-policy">Make-Up Policy</a></li>
  <li><a href="#sick-policy" id="toc-sick-policy" class="nav-link" data-scroll-target="#sick-policy">Sick Policy</a></li>
  <li><a href="#cell-phones-other-electronic-devices" id="toc-cell-phones-other-electronic-devices" class="nav-link" data-scroll-target="#cell-phones-other-electronic-devices">Cell Phones &amp; Other Electronic Devices</a></li>
  </ul></li>
  <li><a href="#grading-scale" id="toc-grading-scale" class="nav-link" data-scroll-target="#grading-scale">Grading Scale</a></li>
  <li><a href="#academic-integrity" id="toc-academic-integrity" class="nav-link" data-scroll-target="#academic-integrity">Academic Integrity</a>
  <ul class="collapse">
  <li><a href="#enforcement-of-academic-integrity-policy" id="toc-enforcement-of-academic-integrity-policy" class="nav-link" data-scroll-target="#enforcement-of-academic-integrity-policy">Enforcement of Academic Integrity Policy</a></li>
  <li><a href="#policy-on-use-of-generative-ai" id="toc-policy-on-use-of-generative-ai" class="nav-link" data-scroll-target="#policy-on-use-of-generative-ai">Policy on Use of Generative AI</a></li>
  </ul></li>
  <li><a href="#principles-of-community" id="toc-principles-of-community" class="nav-link" data-scroll-target="#principles-of-community">Principles of Community</a></li>
  <li><a href="#mental-health-statement" id="toc-mental-health-statement" class="nav-link" data-scroll-target="#mental-health-statement">Mental Health Statement</a>
  <ul class="collapse">
  <li><a href="#need-help" id="toc-need-help" class="nav-link" data-scroll-target="#need-help">Need Help?</a></li>
  <li><a href="#sexual-assault-and-violence-elimination" id="toc-sexual-assault-and-violence-elimination" class="nav-link" data-scroll-target="#sexual-assault-and-violence-elimination">Sexual Assault and Violence Elimination</a></li>
  </ul></li>
  <li><a href="#religious-observances" id="toc-religious-observances" class="nav-link" data-scroll-target="#religious-observances">Religious Observances</a></li>
  <li><a href="#student-resources" id="toc-student-resources" class="nav-link" data-scroll-target="#student-resources">Student Resources</a>
  <ul class="collapse">
  <li><a href="#universal-design-for-learningaccommodation-of-needs" id="toc-universal-design-for-learningaccommodation-of-needs" class="nav-link" data-scroll-target="#universal-design-for-learningaccommodation-of-needs">Universal Design for Learning/Accommodation of Needs</a></li>
  <li><a href="#undocumented-student-support" id="toc-undocumented-student-support" class="nav-link" data-scroll-target="#undocumented-student-support">Undocumented Student Support</a></li>
  <li><a href="#food-insecurity" id="toc-food-insecurity" class="nav-link" data-scroll-target="#food-insecurity">Food Insecurity</a></li>
  <li><a href="#title-ixinterpersonal-violence" id="toc-title-ixinterpersonal-violence" class="nav-link" data-scroll-target="#title-ixinterpersonal-violence">Title IX/Interpersonal Violence</a></li>
  </ul></li>
  <li><a href="#diversity-and-inclusion" id="toc-diversity-and-inclusion" class="nav-link" data-scroll-target="#diversity-and-inclusion">Diversity and Inclusion</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/laurenchenarides/csu-arec-570/edit/main/2025/syllabus.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/laurenchenarides/csu-arec-570/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/laurenchenarides/csu-arec-570/blob/main/2025/syllabus.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="syllabus.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Syllabus</h1>
<p class="subtitle lead">AREC 310 (Fall 2025)</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!--This is my personal clarity, please delete or replace with your own clarity-->
<!-- {{< include /files/includes/_msclarity.qmd >}} -->
<section id="course-information" class="level2">
<h2 class="anchored" data-anchor-id="course-information">Course Information</h2>
<p><strong>Department of Agricultural and Resource Economics</strong></p>
<p><strong>Course Name</strong>: Food and Agricultural Markets</p>
<p><strong>Course Number</strong>: <a href="https://colostate.instructure.com/courses/209950">AREC 310</a> (CRN 66760)</p>
<p><strong>Time</strong>: 9:30 AM - 10:45 AM T R</p>
<p><strong>Location</strong>: ENGRG B 103</p>
<p><strong>Term:</strong> August 25 – December 14, 2025</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Contact Information">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Contact Information
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Instructor</strong>: Dr.&nbsp;Lauren Chenarides</p>
<p><strong>Email</strong>: <a href="mailto:Lauren.Chenarides@colostate.edu" class="email">Lauren.Chenarides@colostate.edu</a></p>
<p><strong>Office Hours:</strong> T 11-noon; Th 2-3 pm</p>
<p><strong>Office Location:</strong> Nutrien 201</p>
<p><strong>Teaching Assistant (TA):</strong> Diya Khatiwada</p>
<p><strong>TA Email</strong>: <a href="mailto:dikshya.khatiwada@colostate.edu" class="email">dikshya.khatiwada@colostate.edu</a></p>
</div>
</div>
</section>
<section id="course-links" class="level2">
<h2 class="anchored" data-anchor-id="course-links">Course Links</h2>
<ul>
<li><a href="https://colostate.instructure.com/courses/209950">Link to Canvas</a></li>
<li><a href="https://laurenchenarides.github.io/csu-arec-310/">Link to Course Website</a></li>
<li><a href="https://hbsp.harvard.edu/import/1227355">Link to Coursepack</a></li>
</ul>
</section>
<section id="course-description" class="level2">
<h2 class="anchored" data-anchor-id="course-description">Course Description</h2>
<p>The food and agricultural sector is one of the most heavily regulated industries in the U.S., as well as globally. This course examines the structure, strategic behavior, and performance of firms in modern food and agricultural markets. Students will study how increasing consolidation and concentration at different stages of the supply chain have enabled the presence of firms with significant seller and buyer market power. Students will learn the economic theory underlying modern food and agricultural markets and then apply it to contemporary case studies where we will examine the economic conduct of agricultural producers, processors, and retailers in a national context. Students will also learn about managing risk, including a review of futures markets.</p>
<p>This course is designed to prepare students with an understanding of key agricultural marketing issues and concerns and to develop students’ analytical skills used so that they may better evaluate different marketing problems and programs to support food and agricultural businesses.</p>
</section>
<section id="prerequisite-arececon-202-principles-of-microeconomics" class="level2">
<h2 class="anchored" data-anchor-id="prerequisite-arececon-202-principles-of-microeconomics">Prerequisite: AREC/ECON 202 (Principles of Microeconomics)</h2>
</section>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<ul>
<li>Understand the functions performed and appreciate the importance and the complexity of the agricultural and food marketing system. (Problem-solving Skill and Professional Development Learning Objectives)</li>
<li>Understand the basic workings of the futures markets for speculators and hedgers, and how these may be used by producers and firms to manage price risk. (Technical Competence Learning Objective)</li>
<li>Be able to apply the basic economic concepts and analytical tools to understand the market forces that affect prices and to be able to use these tools to evaluate markets, prices, and current agricultural marketing issues. (Technical Competence and Problem-solving Skills Learning Objectives)</li>
<li>Refine your ability to think critically and be able to justify your position with relevant economic logic by developing an analytical approach and decision-making framework for economic decisions made by producers &amp; firms in the marketing system. (Communication Skills and Problem-solving Skills Learning Objectives)</li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>DARE Learning Outcomes
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The Department of Agricultural and Resource Economics has identified learning outcomes that each successful graduate will exhibit. AREC 310 contributes to the following learning outcomes.</p>
<p><strong>Professional Development:</strong> Graduates will embody a general awareness of issues in agricultural and natural resource management and their implications in a larger societal context. Students will begin to develop a network of personal and professional connections which will foster an understanding of the culture surrounding professional expectations and conduct.</p>
<p><strong>Technical Competence:</strong> Graduates will demonstrate technical competency including the ability to appropriately use economic theory in formulating analytical problems, identifying and gathering appropriate data, and employing appropriate economic methods to analyze those problems, utilizing appropriate available computer technology.</p>
<p><strong>Problem-solving Skills:</strong> Graduates will demonstrate the ability to solve real-world problems beyond the context of the classroom. Students will be able to identify a problem and its scope, evaluate resources available to address the problem, formulate alternative solutions, and select the solution(s) most consistent with a stated objective.</p>
<p><strong>Communication Skills:</strong> Graduates will demonstrate proficiency in oral and written communication in terms of substance, organization, mechanics, documentation, and synthesis. Proficient students will have the ability to clearly communicate findings, critically and analytically, at a professional level within their chosen career.</p>
</div>
</div>
</div>
</section>
<section id="course-material" class="level2">
<h2 class="anchored" data-anchor-id="course-material">Course Material</h2>
<section id="required" class="level3">
<h3 class="anchored" data-anchor-id="required">Required</h3>
<ul>
<li><strong>Harvard Business Publishing Coursepack</strong><br>
This is a required Excel refresher. Duration: 6 hours.<br>
👉 <a href="https://hbsp.harvard.edu/import/1227355">Access Coursepack Here</a></li>
</ul>
</section>
<section id="optional-resource" class="level3">
<h3 class="anchored" data-anchor-id="optional-resource">Optional Resource</h3>
<ul>
<li><strong>Norwood, F. B., Lusk, J. L., Peel, D. S., &amp; Riley, J. M.</strong> (2021). <em>Agricultural marketing and price analysis.</em> Waveland Press.<br>
This is our core textbook. Weekly lectures will be based on chapters in this textbook. Purchase of the textbook is <strong>not required</strong> for Fall 2025.</li>
</ul>
<p>Additional readings and materials may be posted online throughout the semester.</p>
</section>
</section>
<section id="assignments-grading" class="level2">
<h2 class="anchored" data-anchor-id="assignments-grading">Assignments &amp; Grading</h2>
<p>Final grades will be calculated as follows:</p>
<div style="width:600px">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Item</th>
<th>Total Points Possible</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Midterm Exam</td>
<td>150</td>
</tr>
<tr class="even">
<td>Final Exam</td>
<td>150</td>
</tr>
<tr class="odd">
<td>Homework Assignments</td>
<td>210</td>
</tr>
<tr class="even">
<td>Marketing Project</td>
<td>150</td>
</tr>
</tbody>
</table>
</div>
<section id="grading-policies" class="level3">
<h3 class="anchored" data-anchor-id="grading-policies">Grading Policies</h3>
<ul>
<li><p><strong>Exams:</strong> Two examinations will be offered. Both exams will be worth 150 points each. If you miss the exam for a university excused absence it is your responsibility to make arrangements with me at least 2 weeks before the exam. The exams will be worth 300 points in total.</p></li>
<li><p><strong>Homework:</strong> There will be six homework sets throughout the course that will include problem sets, computer-based exercises, etc. There will also be one introductory bio due at the beginning of the semester. These assignments will be worth approximately 210 points in total. <strong>Late submissions are not accepted.</strong> Any assignment submitted after the deadline will automatically receive a zero.</p></li>
<li><p><strong>Project:</strong> This will be a group project. The project is Excel-based. The project will be worth 150 points.</p></li>
<li><p>All graded components are weighted individually and not curved.</p></li>
</ul>
</section>
<section id="attendance-policy" class="level3">
<h3 class="anchored" data-anchor-id="attendance-policy">Attendance Policy</h3>
<p>Although attendance is not mandatory, it is highly recommended that you attend class.</p>
</section>
<section id="make-up-policy" class="level3">
<h3 class="anchored" data-anchor-id="make-up-policy">Make-Up Policy</h3>
<p>If you anticipate missing a quiz or exam, you must notify the instructor <strong>at least two weeks prior to the absence</strong> and it will be at the discretion of the instructor if a make-up is scheduled. If a make-up is granted, it will only be granted once throughout the entire semester. There are no make-ups for homework.</p>
</section>
<section id="sick-policy" class="level3">
<h3 class="anchored" data-anchor-id="sick-policy">Sick Policy</h3>
<p>If you test positive for COVID, please do not come to class. If you test positive on the day of an exam or your illness coincides with an exam and you were not able to give two weeks’ notice of your absence, please email a doctor’s note to the instructor.</p>
</section>
<section id="cell-phones-other-electronic-devices" class="level3">
<h3 class="anchored" data-anchor-id="cell-phones-other-electronic-devices">Cell Phones &amp; Other Electronic Devices</h3>
<p>Cell phones, etc. must be turned to silent or vibrate mode during class. No texting, emailing, surfing the internet, etc. will be allowed during class.</p>
</section>
</section>
<section id="grading-scale" class="level2">
<h2 class="anchored" data-anchor-id="grading-scale">Grading Scale</h2>
<div style="width:400px">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Grade</th>
<th>Range</th>
<th>Grade</th>
<th>Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A+</td>
<td>100% – 96.67%</td>
<td>C+</td>
<td>79.99% – 76.67%</td>
</tr>
<tr class="even">
<td>A</td>
<td>96.66% – 93.34%</td>
<td>C</td>
<td>76.66% – 70.00%</td>
</tr>
<tr class="odd">
<td>A-</td>
<td>93.33% – 90.00%</td>
<td>D</td>
<td>69.99% – 60.00%</td>
</tr>
<tr class="even">
<td>B+</td>
<td>89.99% – 86.67%</td>
<td>F</td>
<td>&lt; 60.00%</td>
</tr>
<tr class="odd">
<td>B</td>
<td>86.66% – 83.34%</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>B-</td>
<td>83.33% – 80.00%</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
<p><a href="https://canvas.colostate.edu/grading-schemes/"><em>In accordance with Canvas Grading Schemes.</em></a></p>
<blockquote class="blockquote">
<p>Grades are assigned based on demonstrated learning outcomes—not effort alone. However, consistent effort <em>does</em> improve your ability to meet expectations and raise your performance over time.</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What Do These Grades Represent?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>A+ (Exceptional):</strong> Demonstrates <em>mastery</em> of the material with <em>original insight</em> or <em>exceptional quality</em>. Represents the highest level of academic performance and intellectual engagement. Reserved for work that exceeds typical A-level expectations in clarity, depth, and creativity.</li>
<li><strong>A / A- (Excellent):</strong> Indicates strong understanding, analytical skill, and consistent engagement. Work is thorough, well-reasoned, and clearly presented.</li>
<li><strong>B Range (Good):</strong> Solid performance with room for deeper insight or stronger execution. Meets course expectations and reflects a competent grasp of material.</li>
<li><strong>C Range (Satisfactory):</strong> Adequate understanding of core concepts, though analysis may be basic or inconsistently applied.</li>
<li><strong>D (Poor):</strong> Partial understanding or weak demonstration of concepts. Assignments may be incomplete or show significant gaps.</li>
<li><strong>F (Failing):</strong> Inadequate performance or failure to meet minimum course requirements.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="academic-integrity" class="level2">
<h2 class="anchored" data-anchor-id="academic-integrity">Academic Integrity</h2>
<p>Academic misconduct (see examples below) undermines the educational experience at Colorado State University, lowers morale by engendering a skeptical attitude about the quality of education, and negatively affects the relationship between students and faculty/instructors.</p>
<p>Faculty/Instructors are expected to use reasonably practical means of preventing and detecting academic misconduct. Any student found responsible for having engaged in academic misconduct will be subject to academic penalty and/or University disciplinary action.</p>
<p>Students are encouraged to positively impact the academic integrity culture of CSU by reporting incidents of academic misconduct.</p>
<p>Examples of academic misconduct include (but are not limited to):</p>
<ol type="1">
<li><p>Cheating – Cheating includes using unauthorized sources of information and providing or receiving unauthorized assistance on any form of academic work or engaging in any behavior specifically prohibited by the instructor in the course syllabus or class presentation.</p></li>
<li><p>Plagiarism – Plagiarism includes the copying of language, structure, images, ideas, or thoughts of another, and representing them as one’s own without proper acknowledgment, and is related only to work submitted for credit. Also included is the failure to cite sources properly; sources must always be appropriately referenced, whether the source is printed, electronic or spoken.</p></li>
<li><p>Unauthorized Possession or Disposition of Academic Materials – Unauthorized possession or disposition of academic materials includes the unauthorized selling or purchasing of examinations, term papers, or other academic work; stealing another student’s work; and using information from or possessing exams that an instructor did not authorize for release to students.</p></li>
<li><p>Falsification – Falsification encompasses any untruth, either verbal or written, in one’s academic work.</p></li>
<li><p>Facilitation of any act of Academic Misconduct – Facilitation of any act of academic misconduct includes knowingly assisting another to commit an act of misconduct.</p></li>
</ol>
<section id="enforcement-of-academic-integrity-policy" class="level3">
<h3 class="anchored" data-anchor-id="enforcement-of-academic-integrity-policy">Enforcement of Academic Integrity Policy</h3>
<p>Our motivation for rigorously enforcing a no-plagiarism policy is twofold: First, plagiarism is a form of theft. Taking someone else’s words or ideas without attribution is stealing someone else’s work. Second, copying someone else’s work does not fulfill the purpose of the assignment, which is for you to develop critical thinking and analysis skills. You demonstrate this by presenting your own, new, synthesis and analysis in your writing. Simply copying or paraphrasing from source materials does not demonstrate this, however insightful the source(s) may be. Good writing generates new knowledge. This should be your goal in this class, in other courses at CSU and in your career after you leave here.</p>
<p>In this course all written work will be spot checked for plagiarism issues by both instructors and originality checking software such as VeriCite. If you are caught plagiarizing materials you will receive a 0 for the assignment/exam/project, and depending upon the severity of the offense, an F in the course. All examples of plagiarism or academic dishonesty and will be reported to the Office of Conflict Resolution and Student Conduct Services for additional disciplinary action as outlined in the student handbook under the heading <a href="http://catalog.colostate.edu/general-catalog/policies/students-responsibilities/">“academic integrity/Misconduct”</a>.</p>
</section>
<section id="policy-on-use-of-generative-ai" class="level3">
<h3 class="anchored" data-anchor-id="policy-on-use-of-generative-ai">Policy on Use of Generative AI</h3>
<p>You <em>may</em> use generative AI tools (e.g., ChatGPT) as a research assistant to help you solve problems and to help you understand the concepts used in this course. However, if you choose to use such tools, you are claiming the resulting work as your own, and you bear full responsibility for its accuracy and appropriateness. In your assignments, <strong>you must disclose if AI tools were used and how</strong>. Doing so may not harm your grade; rather, it helps me guide you in using these tools effectively to enhance your grasp of the material. Remember, generative AI cannot advocate for itself or provide proper attributions; it is your responsibility to ensure integrity in your work.</p>
</section>
</section>
<section id="principles-of-community" class="level2">
<h2 class="anchored" data-anchor-id="principles-of-community">Principles of Community</h2>
<p>The Principles of Community support the Colorado State University mission and vision of access, research, teaching, service and engagement. A collaborative, and vibrant community is a foundation for learning, critical inquiry, and discovery. Therefore, each member of the CSU community has a responsibility to uphold these principles when engaging with one another and acting on behalf of the University</p>
<p><em>Inclusion</em>: We create and nurture inclusive environments and welcome, value and affirm all members of our community, including their various identities, skills, ideas, talents, and contributions.</p>
<p><em>Integrity</em>: We are accountable for our actions and will act ethically and honestly in all our interactions.</p>
<p><em>Respect</em>: We honor the inherent dignity of all people within an environment where we are committed to freedom of expression, critical discourse, and the advancement of knowledge.</p>
<p><em>Service</em>: We are responsible, individually and collectively, to give of our time, talents, and resources to promote the well-being of each other and the development of our local, regional, and global communities.</p>
<p><em>Social Justice</em>: We have the right to be treated and the responsibility to treat others with fairness and equity, the duty to challenge prejudice, and to uphold the laws, policies and procedures that promote justice in all respects.</p>
</section>
<section id="mental-health-statement" class="level2">
<h2 class="anchored" data-anchor-id="mental-health-statement">Mental Health Statement</h2>
<section id="need-help" class="level3">
<h3 class="anchored" data-anchor-id="need-help">Need Help?</h3>
<p>CSU is a community that cares for you. If you are struggling with drugs or alcohol and/or experiencing depression, anxiety, overwhelming stress or thoughts of hurting yourself or others please know there is help available. Counseling Services has trained professionals who can help. Contact 970.491.6053 or go to http://health.colostate.edu. If you are concerned about a friend or peer, tell someone at by calling 970.491.1350 to discuss your concerns with a professional who can discreetly connect the distressed individual with the proper resources (http://supportandsafety.colostate.edu/tellsomeone). Rams take care of Rams. Reach out and ask for help if you or someone you know is having a difficult time.</p>
</section>
<section id="sexual-assault-and-violence-elimination" class="level3">
<h3 class="anchored" data-anchor-id="sexual-assault-and-violence-elimination">Sexual Assault and Violence Elimination</h3>
<p>CSU’s Student Sexual Harassment and Violence policy, following national guidance from the Office of Civil Rights, requires that professors follow CSU policy as a “mandatory reporter” of any personal disclosure of sexual harassment, abuse, and/or violence related experiences or incidents shared with the professor in person, via email, and/or in classroom papers or homework exercises. These disclosures include but are not limited to reports of personal relational abuse, relational/domestic violence, and stalking. While professors are often able to help students locate appropriate channels of assistance on campus (e.g., see the CSU Health Network link below), disclosure by the student to the professor requires that the professor inform appropriate CSU channels to help ensure that the student’s safety and welfare is being addressed, even if the student requests that the disclosure not be shared.</p>
<p>For counseling support and assistance, please see The CSU HEALTH NETWORK, which includes a variety of counseling services that can be accessed at: <a href="http://www.health.colostate.edu/">http://www.health.colostate.edu/</a>. And, The Sexual Assault Victim Assistance Team is a confidential resource for students that does not have a reporting requirement and that can be of great help to students who have experienced sexual assault. The web address is <a href="http://www.wgac.colostate.edu/need-help-support">http://www.wgac.colostate.edu/need-help-support</a>.</p>
</section>
</section>
<section id="religious-observances" class="level2">
<h2 class="anchored" data-anchor-id="religious-observances">Religious Observances</h2>
<p>CSU does not discriminate on the basis of religion. Reasonable accommodation should be made to allow individuals to observe their established religious holidays.</p>
<p>Please see <a href="https://calendar.colostate.edu/observances/">CSU’s Religious Observances Calendar</a>.</p>
<p>Students seeking an exemption from attending class or completing assigned course work for a religious holiday will need to fill out the <a href="https://studentaffairs.colostate.edu/resources/resources-faculty-staff/administrative-information/religious-holidays/">Religious Accommodation Request Form</a> and turn it in to the Division of Student Affairs, located on the second level of the Administration building.</p>
<p>Once turned in, the Division of Student Affairs will review the request and contact the student accordingly. If approved, the student will receive a memo from the Dean of Students to give to their professor or course instructor.</p>
<p>Students are asked to turn in the request forms as soon as the conflict is noticed. Similarly, unanticipated conflicts requiring a religious observance, such as a death in the family, can also be reviewed.</p>
</section>
<section id="student-resources" class="level2">
<h2 class="anchored" data-anchor-id="student-resources">Student Resources</h2>
<section id="universal-design-for-learningaccommodation-of-needs" class="level3">
<h3 class="anchored" data-anchor-id="universal-design-for-learningaccommodation-of-needs">Universal Design for Learning/Accommodation of Needs</h3>
<p>I am committed to the principle of universal learning. This means that our classroom, our virtual spaces, our practices, and our interactions be as inclusive as possible. Mutual respect, civility, and the ability to listen and observe others carefully are crucial to universal learning. If you are a student who will need accommodations in this class, please contact me to discuss your individual needs. Any accommodation must be discussed in a timely manner. A verifying memo from <a href="https://disabilitycenter.colostate.edu/">The Student Disability Center</a> may be required before any accommodation is provided. I ask that students that require accommodations that are not met by the standard course set up to arrange a time to discuss the accommodation with me.</p>
<p>The Student Disability Center (SDC) has the authority to verify and confirm the eligibility of students with disabilities for the majority of accommodations. While some accommodations may be provided by other departments, a student is not automatically eligible for those accommodations unless their disability can be verified and the need for the accommodation confirmed, either through SDC or through acceptable means defined by the particular department. Faculty and staff may consult with the SDC staff whenever there is doubt as to the appropriateness of an accommodative request by a student with a disability.</p>
<p>The goal of SDC is to normalize disability as part of the culture of diversity at Colorado State University. The characteristic of having a disability simply provides the basis of the support that is available to students. The goal is to ensure students with disabilities have the opportunity to be as successful as they have the capability to be.</p>
<p>Support and services are offered to student with functional limitations due to visual, hearing, learning, or mobility disabilities as well as to students who have specific physical or mental health conditions due to epilepsy, diabetes, asthma, AIDS, psychiatric diagnoses, etc. Students who are temporarily disabled are also eligible for support and assistance.</p>
<p>Any student who is enrolled at CSU, and who self-identifies with SDC as having a disability, is eligible for support from SDC. Specific accommodations are determined individually for each student and must be supported by appropriate documentation and/or evaluation of needs consistent with a particular type of disability. SDC reserves the right to ask for any appropriate documentation of disability in order to determine a student’s eligibility for accommodations as well as in support for specific accommodative requests. The accommodative process begins once a student meets with an accommodation’s specialist in the SDC.</p>
<p>If the student requires an accommodation for in-person exams/quizzes, they must arrange for the accommodation by the SDC Accessible Testing Center.</p>
</section>
<section id="undocumented-student-support" class="level3">
<h3 class="anchored" data-anchor-id="undocumented-student-support">Undocumented Student Support</h3>
<p>Any CSU student who faces challenges or hardships due to their legal status in the United States and believes that it may impact their academic performance in this course is encouraged to visit <a href="https://undocumented.colostate.edu/">Student Support Services for Undocumented, DACA &amp; ASSET</a> for resources and support. Additionally, only if you feel comfortable, please notify your professor so they may pass along any additional resources they may possess.</p>
</section>
<section id="food-insecurity" class="level3">
<h3 class="anchored" data-anchor-id="food-insecurity">Food Insecurity</h3>
<p>Any CSU student (along with faculty and staff) who is experiencing food insecurity can receive support from the <a href="https://lsc.colostate.edu/slice/slice-engagement/rams-against-hunger/">Rams Against Hunger</a> program. Services include a food pantry, a meal-swipe program, pocket pantries, and in-person assistance with navigating federal aid eligibility. The RAH page includes numerous resources as well as county, state and federal programs which are described and linked.</p>
</section>
<section id="title-ixinterpersonal-violence" class="level3">
<h3 class="anchored" data-anchor-id="title-ixinterpersonal-violence">Title IX/Interpersonal Violence</h3>
<p>For the full statement regarding role and responsibilities about reporting harassment, sexual harassment, sexual misconduct, domestic violence, dating violence, stalking, and the retaliation policy please go to: <a href="http://oeo.colostate.edu/title-ix-sexual-assault">Title IX – Sexual Assault, Sexual Violence, Sexual Harassment</a>.</p>
<p>If you feel that your rights have been compromised at CSU, several resources are available to assist:</p>
<ul>
<li>Student Resolution Center, 200 Lory Student Center, 491-7165</li>
<li>Office of Equal Opportunity, 101 Student Services, 491-5836</li>
</ul>
<p>A note about interpersonal violence: If you or someone you know has experienced sexual assault, relationship violence and/or stalking, know that you are not alone. As instructors, we are required by law to notify university officials about disclosures related to interpersonal violence. Confidential victim advocates are available 24 hours a day, 365 days a year to provide support related to the emotional, physical, physiological and legal aftermath of interpersonal violence. Contact the Victim Assistance Team at: 970-492-4242.</p>
</section>
</section>
<section id="diversity-and-inclusion" class="level2">
<h2 class="anchored" data-anchor-id="diversity-and-inclusion">Diversity and Inclusion</h2>
<p>In an ideal world, science would be objective. However, much of science is subjective and is historically built on a small subset of privileged voices. I acknowledge that many of the readings for this course were authored by white men. Furthermore, the course often focuses on economic principles, policies, and concepts that were mostly developed by white men. I have made recent edits to the materials to try to reflect a more diverse perspective. However, I acknowledge that it is possible that there may be both overt and covert biases in the material due to the lens with which it was written, even though the material is primarily of a scientific nature. Integrating a diverse set of experiences is important for a more comprehensive understanding of science. Please contact me (in person or via Canvas) or submit anonymous feedback if you have any suggestions to improve the quality of the course materials (I have a paper mailbox on the second floor of Nutrien if you are worried about leaving an electronic trace). I would like to create a learning environment for my students that supports a diversity of thoughts, perspectives and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, etc.) To help accomplish this:</p>
<ul>
<li>If you have a name and/or set of pronouns that differ from those that appear in your official CSU records, please let me know!</li>
<li>If you feel like your performance in the class is being impacted by your experiences outside of class, please don’t hesitate to come and talk with me. I want to be a resource for you. Remember that you can also submit anonymous feedback (which will lead to me making a general announcement to the class, if necessary to address your concerns). If you prefer to speak with someone outside of the course, the Vice President for Student Affairs is an excellent resource.</li>
<li>I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. (Again, anonymous feedback is always an option).</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/laurenchenarides\.github\.io\/csu-arec-570");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="https://github.com/laurenchenarides/csu-arec-570">Lauren Chenarides</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/laurenchenarides/csu-arec-570/edit/main/2025/syllabus.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/laurenchenarides/csu-arec-570/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/laurenchenarides/csu-arec-570/blob/main/2025/syllabus.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/laurenchenarides/csu-arec-570">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>